swagger: '2.0'
info:
  version: 1.0.0
  title: Webtask API

host: webtask.it.auth0.com

schemes:
- https

paths:
  /api/tokens/issue:
    post:
      produces:
        - application/json   
      parameters:
      - in: header
        name: Authorization
        required: true
        description: Your webtask token
        type: string 
      - in: body
        name: Webtask
        type: object
        schema:
          $ref: '#/definitions/Webtask'      
      responses:
        200:
          description: Webtask token created
        400:
          description: Bad request
        403:
          description: The webtask token was not provided or does not have sufficient permissions

definitions:
  Webtask:
    type: object
    properties:
      ten:
        type: string
        example: my-container
      jtn:
        type: string
        example: my-webtask-name 
      code:
        type: string
        description: Pass in the code that the webtask will run on every request.
        example: "module.exports = function(cb) { cb(null, { message: 'Hello Webtasks!'});"               
      