swagger: '2.0'
info:
  version: 1.0.0
  title: Webtask API

host: webtask.it.auth0.com

schemes:
- https

paths:
  /api/tokens/inspect:
    get:
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        required: true
        description: Your webtask token
        type: string
      - in: query
        name: token
        description: The webtask token to be inspected.
        type: string
        required: true
      - in: query
        name: fetch_code
        description: When inspecting a webtask token with fixed code , the fetch_code query parameter can be set to true in order to resolve any stored code before sending the response. The webtask's code will be available in the code property of the response body.
        type: boolean
        default: false
      - in: query
        name: decrypt
        description: When inspecting a webtask token with encrypted secrets , the decrypt query parameter can be set to true in order to decrypt any secrets before sending the response. The decrypted secrets will be available in the secrets property of the response body as a javascript object mapping secret names to their values.
        type: boolean
        default: false        
      responses:
        200:
          description: The inspected data.
        403:
          description: The webtask token was not provided or does not have sufficient permissions          
