swagger: '2.0'
info:
  version: 1.0.0
  title: Webtask API

host: webtask.it.auth0.com

schemes:
- https

paths:
  /api/tokens/issue:
    post:
      produces:
        - application/json   
      parameters:
      - in: header
        name: Authorization
        required: true
        description: Your webtask token
        type: string 
      - in: body
        name: Webtask
        type: object
        schema:
          $ref: '#/definitions/Webtask'      
      responses:
        200:
          description: The token has been successful revoked.
        400:
          description: Bad request
        403:
          description: The webtask token was not provided or does not have sufficient permissions

definitions:
  Webtask:
    type: object
    properties:
      token:
        type: string
        example: ey...