swagger: '2.0'
info:
  version: 1.0.0
  title: Webtask API

host: webtask.it.auth0.com

schemes:
- https

paths:
  /api/webtask/{webtask_container}:
    delete:
      produces:
      - application/json
      parameters:
      - in: path
        name: webtask_container
        description: Your webtask container
        required: true
        type: string       
      - in: header
        name: Authorization
        required: true
        description: Your webtask token
        type: string
      responses:
        204:
          description: Cache has been successfuly cleaned up and some artifacts were removed in the process
        403:
          description: The webtask token was not provided or does not have sufficient permissions
        404:
          description: Cache did not contain any artifacts to be removed

  /api/webtask/{webtask_container}/{webtask_name}:
    delete:
      description: To delete cached data of a single webtask
      produces:
      - application/json
      parameters:
      - in: path
        name: webtask_container
        description: Your webtask container
        required: true
        type: string
      - in: path
        name: webtask_name
        description: The name of the webtask
        required: true
        type: string        
      - in: header
        name: Authorization
        required: true
        description: Your webtask token
        type: string
      responses:
        204:
          description: Cache has been successfuly cleaned up and some artifacts were removed in the process.
        403:
          description: The webtask token is not submitted with the request or does not grant sufficient permissions.
        404:
          description: Cache did not contain any artifacts to be removed.          